### ISSUE TITLE
Binary Packages

### ISSUE THREAD

**Issue by vext01** [softdevteam/krun-linux-kernel#9]
I have binary deb packages for the new 4.9.30 krun kernel. I was thinking of putting them up on archive.org for distribution to users.

`make deb-pkg` makes the following files:
```
4.0K	linux-4.9.30krun.ac72888e_4.9.30krun.ac72888e-2_amd64.changes
4.0K	linux-4.9.30krun.ac72888e_4.9.30krun.ac72888e-2.debian.tar.gz
4.0K	linux-4.9.30krun.ac72888e_4.9.30krun.ac72888e-2.dsc
140M	linux-4.9.30krun.ac72888e_4.9.30krun.ac72888e.orig.tar.gz
11M	linux-headers-4.9.30krun.ac72888e_4.9.30krun.ac72888e-2_amd64.deb
37M	linux-image-4.9.30krun.ac72888e_4.9.30krun.ac72888e-2_amd64.deb
522M	linux-image-4.9.30krun.ac72888e-dbg_4.9.30krun.ac72888e-2_amd64.deb
852K	linux-libc-dev_4.9.30krun.ac72888e-2_amd64.deb
```

The `krun.ac72888e` part of each filename is the kernel's "local version". I've included the first 8 characters of the git version hash in this string so we know exactly where the packages come from. Don't ask me why `make deb-pkg` includes the version string twice. I think we are free to rename these files, but it might confuse people who are familiar with `make deb-pkg`. I guess I'd prefer to leave them as-is.

Which of these files shall we distribute?

We need at least:
```
37M	linux-image-4.9.30krun.ac72888e_4.9.30krun.ac72888e-2_amd64.deb
852K	linux-libc-dev_4.9.30krun.ac72888e-2_amd64.deb
```

The former is the kernel itself, the latter is the glibc header with our custom syscall numbers in.

 * The debug deb is the kernel with debug symbols, it's huge.
 * The headers deb are kernel headers. These should be identical to the ones debian provide.
 * The tarballs are presumably source code before and after.
 * The changes files contains checksums of the other files. Weird name...
 * The dsc file is https://wiki.debian.org/dsc

I'm going to recommend, we distribute:

 * `linux-image-4.9.30krun.ac72888e_4.9.30krun.ac72888e-2_amd64.deb`
 * `linux-libc-dev_4.9.30krun.ac72888e-2_amd64.deb`
 * The after-changes source tarball, to protect us from GPL shenanigans.

What do you think @ltratt?

A documentation change will follow once we have this sorted out.

**Comment by vext01** [comment]
I was wrong about the tarballs.

`linux-4.9.30krun.ac72888e_4.9.30krun.ac72888e-2.debian.tar.gz` contains a handful of boring files:

```
changelog  control  copyright  rules
```

`linux-4.9.30krun.ac72888e_4.9.30krun.ac72888e.orig.tar.gz` is source code, but it's had the `README.md`  (and what else?) stripped, which we probably want to keep.

We can either just make our own tarball, or if the license lets us, just make a diff to the debian sources.

**Comment by ltratt** [comment]
I'm happy with whatever you suggest.

**Comment by vext01** [comment]
Just looking at gnu.org:
```
if you release the modified version to the public in some way, the GPL requires you to make the modified source code available to the program's users, under the GPL.
```

I'm not sure if we are OK to distribute a diff of not, but some part of me thinks we should simply tar up the debian sources with our changes on top. The thing is, the source code is quite large. Hrm...

**Comment by vext01** [comment]
Let's make a diff. I don't think it's fair on archive.org to keep uploading 150MB tarballs for each new version.

Once #8 is merged, I will make new debs and the diff.

**Comment by ltratt** [comment]
Agreed.

**Comment by vext01** [comment]
Building new debs now...
